version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "somagroo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zt75hcyx82sd"
s3_prefix = "somagroo"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
